on:
  pull_request:
    paths:
    - 'auth-server-ws/**'
    - '.github/workflows/build-auth-server.yml'
name: Build-auth-server-ws
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Check out pull request's HEAD commit instead of the merge commit to
        # work-around an issue where wrong a commit is being checked out.
        # For more details, see:
        # https://github.com/actions/checkout/issues/299.
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
          cd auth-server-ws
          mvn -B package --file pom.xml
