name: Build-iOS
on:
  pull_request:
    paths:
    - 'iOS/**'
    - '.github/workflows/build-iOS.yml'
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.6,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Check out pull request's HEAD commit instead of the merge commit to
          # work-around an issue where wrong a commit is being checked out.
          # For more details, see:
          # https://github.com/actions/checkout/issues/299.
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build
        run: |
          cd iOS/HPHC
          xcodebuild clean build -workspace HPHC.xcworkspace -scheme HPHC -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES
        env: 
         destination: ${{ matrix.destination }}
