on:
  pull_request:
    paths:
    - 'common-service/**'
    - '.github/workflows/build-common-service.yml'
name: Build-common-service
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
          cd common-service
          mvn -B package --file pom.xml
