name: SwiftLint

on:
  pull_request:
    paths:
      - 'iOS/**'
      - '.github/workflows/swiftlint.yml'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Check out pull request's HEAD commit instead of the merge commit to
          # work-around an issue where wrong a commit is being checked out.
          # For more details, see:
          # https://github.com/actions/checkout/issues/299.
          ref: ${{ github.event.pull_request.head.sha }}
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --path iOS/HPHC --config .swiftlint.yml
