# This Git hub action workflows to keep pairs of git repos in sync.
# It runs on a Schedule time set by the user in the script. 
# Shortly after changes are made to the default branch of repo A, the Actions workflow runs on repo B and generates a pull request including the recent changes from repo A. 
# If more changes are made to repo A before the pull request is merged, those changes will be added to the existing pull request. 
# The same is true in the opposite direction: changes made to repo B will eventually get picked up by the workflow in repo A.
# For more information please refer thislink: https://github.com/repo-sync/repo-sync
name: Repo Sync

on:
  schedule: 
  - cron: "*/30 06 * * *" # It runs every day 6:00 UTC. set to whatever interval you like
    
    

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: ${{ secrets.SOURCE_REPO }}
        source_branch: develop
        destination_branch: ${{ secrets.INTERMEDIATE_BRANCH }}
        github_token: ${{ secrets.PERSONAL_KEY }}
    - uses: repo-sync/pull-request@v2
      name: Create pull request
      with:
        source_branch: ${{ secrets.INTERMEDIATE_BRANCH }}
        destination_branch: develop
        github_token: ${{ secrets.PERSONAL_KEY }}
